version: '3.0'
services:
  fetcher:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_db:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysql_db: