version: '3.0'
services:
  fetcher:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb_container
  mongodb_container:
    image: mongo:latest
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: