name: Docker Image CI

on:
  push:
    branches: [ "feature/**" ]


jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      PORT: 8000

    steps:
    - uses: actions/checkout@v3
    - name: Build the docker-compose stack
      run: docker-compose -f docker-compose.yml up -d
    - name: Check running containers
      run: docker ps -a
    - name: Check logs
      run: docker logs backend
